### PR TITLE
Do not list folders as files

### PR DESCRIPTION
**Pull request by rastakajakwanna**
Folder was previously displayed as a file with 0 size. This change fixes it.

Before this change:
image

After:
image

### CODE REVIEW

**Comment by flightlesstux** [comment]
Hello @rastakajakwanna,

Thank you so much for your contribution! Could you create some folder in folder in folder something like this. I mean, could you add do-not-list-folders/do-not-list-folders-1/do-not-list-folders-2/do-not-list-folders-3 with empty folders? The PR should include this.

Best!

**Comment by rastakajakwanna** [comment]
You mean like this? 😄 
image

I am sorry, I don't get it 😃 😃 I also don't see any Contributing.md file in your repository which would explain it... Where did you get this?
> ... could you add do-not-list-folders/do-not-list-folders-1/do-not-list-folders-2/do-not-list-folders-3 with empty folders?  The PR should include this.

**Comment by rastakajakwanna** [comment]
Oh.. you mean I have to add the folders in the PR, , right?🤦‍♂️ I'll do it ... sorry 😄

**Comment by flightlesstux** [comment]
> You mean like this? 😄 image
> 
> I am sorry, I don't get it 😃 😃 I also don't see any Contributing.md file in your repository which would explain it... Where did you get this?
> 
> > ... could you add do-not-list-folders/do-not-list-folders-1/do-not-list-folders-2/do-not-list-folders-3 with empty folders?  The PR should include this.

This repository doesn't contains `Contributing.md` file but if you want to add, you are free : ) 

Just add the empty folder directly to your PR because when the PR is merged, the demo link and demo s3 bucket will update with the new feature (or bugfix) and we should show the feature in the demo, this is the reason. Thank you! 🙏🏻

**Review by flightlesstux — CHANGES_REQUESTED** [review]
What will happend this step start for 2nd time, 3rd time, 4th time? : ) Just add the folder into your PR with .gitkeep and that's it.

**Comment by flightlesstux** [comment]
> Hi @flightlesstux , pardon my ignorance but I really don't get what you need :) I obviously cannot commit empty folders unless I do a trick with .gitkeep, I also don't see a reason for doing it as I don't see any automation expecting some empty folders, and finally, I don't see any previous PR containing these (to learn from).
> 
> The change in this PR fixed a problem for me while running your code behind authenticated ALB with private S3. I couldn't find any difference between xml from your public S3 and the xml forwarded by my ALB first, but I found the difference today. My s3 adds the folder as key while yours does not. I am not sure if it is because the bucket is in the ap-southeast-2 region (regional bug) or because it is exposed using the vpc endpoint interfaces with ALB (I'll probably ask AWS support about it), but that's what is causing it.
> 
> You skip folder (if path) in the prefixes for loop, but you don't do that in the keys for loop (as you don't expect it), but you probably should, kindly see the xml samples below.
> 
> Considering the differences, it seems to me this PR code change does not break anything for your setup while it fixes things for my setup and others might benefit from it 😃
> 
> Your s3 xml within test-folder-1
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> <Name>s3-directory-listing</Name>
> <Prefix>test-folder-1/</Prefix>
> <KeyCount>3</KeyCount>
> <MaxKeys>1000</MaxKeys>
> <Delimiter>/</Delimiter>
> <IsTruncated>false</IsTruncated>
> <Contents>
>   <Key>test-folder-1/folder-1.file</Key><LastModified>2024-05-07T21:31:48.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass>
> </Contents>
> <Contents>
>   <Key>test-folder-1/folder-2.file</Key><LastModified>2024-05-07T21:31:48.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass></Contents>
> <Contents>
>   <Key>test-folder-1/folder-3.file</Key><LastModified>2024-05-07T21:31:48.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass>
> </Contents>
> </ListBucketResult>
> ```
> 
> My s3 xml within data folder
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> <Name>-removed-</Name>
> <Prefix>data/</Prefix>
> <KeyCount>2</KeyCount>
> <MaxKeys>1000</MaxKeys>
> <Delimiter>/</Delimiter>
> <IsTruncated>false</IsTruncated>
> <Contents>
>   <Key>data/</Key><LastModified>2024-11-25T14:37:17.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass>
> </Contents>
> <Contents>
>   <Key>data/in_folder.txt</Key><LastModified>2024-11-25T16:25:59.000Z</LastModified><ETag>&quot;5217d6037c161db733d7eab74520d802&quot;</ETag><Size>11</Size><StorageClass>STANDARD</StorageClass>
> </Contents>
> </ListBucketResult>
> ```
> 
> UPDATE: You replied while I was writing my reply :) . Thanks for the explanation but I think my point still stands. This is not a new feature, it's a bugfix for some rare case and the change isn't and won't be visible in your setup because that does not suffer from this rare case, thus adding more folders does not make sense :)
> 
> UPDATE2: I've just realized there's nothing rare about it! It's just a difference between AWS Console S3 folder (creates a 0-size object with a specified name) and file prefix. Both look like a file structure (but only for Console visualisation purposes), but there is a difference when it comes to raw representation. That means my tiny bugfix solves the case when you manually create a folder in AWS S3 Console. It also probably means this case cannot be represented by your current github action using empty folder (even with the .gitkeep workaround). I'll try to update my PR to contain one extra github action to represent this case.

It doesn't matter is it bug or feature or new release. At the end, we are fixing the list folder if it's in folder and that is it. Right?

**Comment by rastakajakwanna** [comment]
> What will happend this step start for 2nd time, 3rd time, 4th time?

Nothing, this api call is immutable.

See for yourself, here's my test.
```
[21:04:36] ~ $ aws s3api put-object --bucket test-bucket --key folder-test-case/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
[21:04:52] ~ $ aws s3api put-object --bucket test-bucket --key folder-test-case/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
[21:04:55] ~ $ aws s3api put-object --bucket test-bucket --key folder-test-case/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
```
(etag is the same because it is a checksum and that's the result for a 0-byte object)

> It doesn't matter is it bug or feature or new release. At the end, we are fixing the list folder if it's in folder and that is it. Right?

You're right, it doesn't matter what it is, what matters is if we understand the problem correctly, thus my super-long text and attempts to validate my statements.
No, we are not fixing "the list folder if it's in folder".  "Folder" object (as I suggest) is different from file object with prefix (as you request). Please compare XML from my previous post or [3] with [1],[2]

> Just add the folder into your PR with .gitkeep and that's it.

No, it won't work, s3 sync would make it as file with prefix [0],[1],[2]. It won't create a folder in folder and file.

[0]
```
[21:14:03] /tmp $ mkdir -p test-dir/nested-1/nested-2
[21:14:08] /tmp $ cd test-dir/
[21:14:15] /tmp/test-dir $ touch nested-1/nested-2/.gitkeep
[21:14:32] /tmp/test-dir $ tree -a
.
└── nested-1
    └── nested-2
        └── .gitkeep

3 directories, 1 file
[21:14:34] /tmp/test-dir $ aws s3 sync . s3://test-bucket/
upload: nested-1/nested-2/.gitkeep to s3://test-bucket/nested-1/nested-2/.gitkeep
```
[1]
```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>test-bucket</Name>
<Prefix>nested-1/</Prefix>
<KeyCount>1</KeyCount>
<MaxKeys>1000</MaxKeys>
<Delimiter>/</Delimiter>
<IsTruncated>false</IsTruncated>
<CommonPrefixes>
  <Prefix>nested-1/nested-2/</Prefix>
</CommonPrefixes>
</ListBucketResult>
```
[2]
```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>test-bucket</Name>
<Prefix>nested-1/nested-2/</Prefix>
<KeyCount>1</KeyCount>
<MaxKeys>1000</MaxKeys>
<Delimiter>/</Delimiter>
<IsTruncated>false</IsTruncated>
<Contents>
  <Key>nested-1/nested-2/.gitkeep</Key>
  <LastModified>2024-11-26T20:14:46.000Z</LastModified>
  <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
  <Size>0</Size>
  <StorageClass>STANDARD</StorageClass>
</Contents>
</ListBucketResult>
```

Now compare it with this:
```
21:34:06] /tmp/test-dir $ aws s3api put-object --bucket test-bucket --key nested-3/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
[21:34:44] /tmp/test-dir $ aws s3api put-object --bucket test-bucket --key nested-3/.gitkeep
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
[21:34:57] /tmp/test-dir $ echo "not-null-object" > notnull
[21:37:16] /tmp/test-dir $ aws s3api put-object --bucket test-bucket --key nested-3/notnull --body notnull 
{
    "ETag": "\"5c5f9d6b8b98e867b8b0b66e37241fe0\"",
    "ServerSideEncryption": "AES256"
}
```

[3] Let's check the XML now
```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>test-bucket</Name>
<Prefix>nested-3/</Prefix>
<KeyCount>3</KeyCount>
<MaxKeys>1000</MaxKeys>
<Delimiter>/</Delimiter>
<IsTruncated>false</IsTruncated>
<Contents>
  <Key>nested-3/</Key>
  <LastModified>2024-11-26T20:34:45.000Z</LastModified>
  <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
  <Size>0</Size>
  <StorageClass>STANDARD</StorageClass>
</Contents>
<Contents>
  <Key>nested-3/.gitkeep</Key>
  <LastModified>2024-11-26T20:34:57.000Z</LastModified>
  <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
  <Size>0</Size>
  <StorageClass>STANDARD</StorageClass>
</Contents>
<Contents>
  <Key>nested-3/notnull</Key>
  <LastModified>2024-11-26T20:37:39.000Z</LastModified>
  <ETag>"5c5f9d6b8b98e867b8b0b66e37241fe0"</ETag>
  <Size>16</Size>
  <StorageClass>STANDARD</StorageClass>
</Contents>
</ListBucketResult>
```
See? The "nested-3" is created as an object and thus listed as an object between other objects.

Therefore the only way to create the folder object is adding the github action task with a separate s3 call as I've suggested.

**Comment by flightlesstux** [comment]
Hello @rastakajakwanna, thank you so much for the detailed explanation. PR is approved!

**Review by flightlesstux — APPROVED** [review]
LGTM!

**Pull request merged**
